### ISSUE TITLE
TYPO3 v13 compatibility ?

### ISSUE THREAD

**Issue by mtness** [b13/trusted-url-params#9]

**Comment by bmack** [comment]
Hey @mtness ,

personally, I don't think this extension is needed anymore for v13. Check out this new change: https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-98488-TypolinkOptionAddQueryStringOnlyIncludesResolvedQueryArguments.html#breaking-98488-typolink-option-addquerystring-only-includes-resolved-query-arguments

which I built into Core for v12 - because I couldn't do it earlier, as it is a breaking change.

**Comment by mtness** [comment]
Ok, understood.Thank you and have a nice weekend!
